version: "3"
services:
  mysql:
    network_mode: host
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ffruignea
      MYSQL_DATABASE: ffru
      MYSQL_USER: strapi
      MYSQL_PASSWORD: ffruignea
